spring.application.name=actuators-customise
management.endpoints.web.exposure.include=*
management.endpoint.info.enabled=true
management.endpoint.env.enabled=true
info.app.name=actuators
info.app.version=1
info.app.owner=anu
management.endpoints.web.base-path=/manage
